const state={projects:[],category:"All",search:"",sort:"order"};
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
async function loadProjects(){try{const r=await fetch("projects.json?cache="+Date.now());if(!r.ok)throw Error();state.projects=(await r.json()).filter(p=>p.visible!==false);renderCategories();renderStats();renderFeatured();renderProjects()}catch(e){$("projectGrid").innerHTML='<div class="empty-state"><h2>Projects could not load</h2></div>'}}
function filtered(){let a=[...state.projects];if(state.category!=="All")a=a.filter(p=>p.category===state.category);if(state.search){const q=state.search.toLowerCase();a=a.filter(p=>`${p.name} ${p.shortDescription} ${p.description} ${p.category}`.toLowerCase().includes(q))}if(state.sort==="updated")a.sort((a,b)=>String(b.lastUpdated).localeCompare(String(a.lastUpdated)));else if(state.sort==="name")a.sort((a,b)=>a.name.localeCompare(b.name));else a.sort((a,b)=>(a.order||999)-(b.order||999));return a}
function renderCategories(){const cats=["All",...new Set(state.projects.map(p=>p.category).filter(Boolean))];$("categoryNav").innerHTML=cats.map(c=>`<button class="${c===state.category?"active":""}" data-category="${esc(c)}">${esc(c)}</button>`).join("");document.querySelectorAll("[data-category]").forEach(b=>b.onclick=()=>{state.category=b.dataset.category;renderCategories();renderProjects()})}
function renderStats(){$("statProjects").textContent=state.projects.length;$("statCategories").textContent=new Set(state.projects.map(p=>p.category)).size;$("statDownloads").textContent=state.projects.filter(p=>p.localUse).length;const d=new Date();d.setDate(d.getDate()-30);$("statUpdated").textContent=state.projects.filter(p=>new Date(p.lastUpdated)>=d).length}
function art(p){return p.coverImage?`<img src="${esc(p.coverImage)}" alt="${esc(p.name)}">`:`<span class="project-icon">${esc(p.icon||"🧩")}</span>`}
function renderFeatured(){const a=state.projects.filter(p=>p.featured).sort((x,y)=>(x.order||999)-(y.order||999)).slice(0,2);$("featuredSection").innerHTML=a.map(p=>`<article class="featured-card"><div class="featured-copy"><p class="eyebrow">${esc(p.category)}</p><h2>${esc(p.name)}</h2><p>${esc(p.shortDescription||p.description)}</p><div class="featured-actions">${p.website?`<a class="button primary" target="_blank" href="${esc(p.website)}">Open Project</a>`:""}<button class="button secondary" data-details="${esc(p.id)}">View Details</button></div></div><div class="featured-art">${art(p)}</div></article>`).join("");bind()}
function renderProjects(){const a=filtered();$("resultText").textContent=`${a.length} project${a.length===1?"":"s"} shown`;$("projectGrid").innerHTML=a.length?a.map(p=>`<article class="project-card"><div class="project-cover"><span class="project-status">${esc(p.status||"Available")}</span>${art(p)}</div><div class="project-body"><p class="eyebrow">${esc(p.category)}</p><h3>${esc(p.name)}</h3><p>${esc(p.shortDescription||"")}</p><div class="project-meta"><span>v${esc(p.version||"Latest")}</span><span>${esc(p.lastUpdated||"")}</span></div><div class="project-actions">${p.website?`<a class="button primary" target="_blank" href="${esc(p.website)}">Open</a>`:""}${p.download&&p.localUse?`<a class="button secondary" href="${esc(p.download)}">Download</a>`:""}<button class="details-button" data-details="${esc(p.id)}">View details</button></div></div></article>`).join(""):'<div class="empty-state"><h2>No matching projects</h2></div>';bind()}
function bind(){document.querySelectorAll("[data-details]").forEach(b=>b.onclick=()=>openDialog(b.dataset.details))}
function setLink(id,url){const a=$(id);a.hidden=!url;if(url)a.href=url}
function openDialog(id){const p=state.projects.find(x=>x.id===id);if(!p)return;$("dialogCover").innerHTML=art(p);$("dialogCategory").textContent=p.category||"Project";$("dialogName").textContent=p.name;$("dialogDescription").textContent=p.description||p.shortDescription||"";$("dialogVersion").textContent=p.version||"Latest";$("dialogStatus").textContent=p.status||"Available";$("dialogUpdated").textContent=p.lastUpdated||"Not listed";$("dialogLocal").textContent=p.localUse?"Yes":"No";$("dialogChangelog").textContent=p.changelog||"No changelog added.";setLink("dialogWebsite",p.website);setLink("dialogGithub",p.github);setLink("dialogDownload",p.download&&p.localUse?p.download:"");$("projectDialog").showModal()}
$("searchInput").oninput=e=>{state.search=e.target.value.trim();renderProjects()};$("sortSelect").onchange=e=>{state.sort=e.target.value;renderProjects()};$("dialogClose").onclick=()=>$("projectDialog").close();$("projectDialog").onclick=e=>{if(e.target===$("projectDialog"))$("projectDialog").close()};$("themeButton").onclick=()=>{document.body.classList.toggle("dark");const d=document.body.classList.contains("dark");localStorage.setItem("bowProjectTheme",d?"dark":"light");$("themeButton").textContent=d?"☀️":"🌙"};if(localStorage.getItem("bowProjectTheme")==="dark"){document.body.classList.add("dark");$("themeButton").textContent="☀️"}loadProjects();